[package]
name = "glide-graph"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
glide-common = { workspace = true }
rusqlite = { workspace = true }
chrono = { workspace = true }
git2 = { workspace = true }
globset = { workspace = true }
ignore = { workspace = true }
walkdir = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
